"""Add desired_work_days to User model

Revision ID: 0b4f9c89f982
Revises: b7b67dad01a6
Create Date: 2026-02-14 22:13:19.789927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4f9c89f982'
down_revision = 'b7b67dad01a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_work_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('desired_work_days')

    # ### end Alembic commands ###
