"""Add composite unique constraint to special_days

Revision ID: 15d8b35a3a42
Revises: 193cecf9c9b2
Create Date: 2026-03-14 12:13:19.293479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d8b35a3a42'
down_revision = '193cecf9c9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_days', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_special_days_date'), type_='unique')
        batch_op.create_unique_constraint('uq_special_days_date_visit_time', ['date', 'visit_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_days', schema=None) as batch_op:
        batch_op.drop_constraint('uq_special_days_date_visit_time', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_special_days_date'), ['date'])

    # ### end Alembic commands ###
