"""Add shift_history table

Revision ID: 193cecf9c9b2
Revises: f4a6388ff38d
Create Date: 2026-03-08 08:06:53.313243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193cecf9c9b2'
down_revision = 'f4a6388ff38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], name=op.f('fk_shift_history_shift_type_id_shift_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shift_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_history'))
    )
    with op.batch_alter_table('shift_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_shift_history_date'))

    op.drop_table('shift_history')
    # ### end Alembic commands ###
