"""add part time shift limits

Revision ID: 3032890fc90d
Revises: 0b4f9c89f982
Create Date: 2026-02-16 17:29:05.761616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3032890fc90d'
down_revision = '0b4f9c89f982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    shift_constraints_table = sa.table(
        "shift_constraints",
        sa.column("name", sa.String),
        sa.column("value", sa.Integer),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        shift_constraints_table,
        [
            {'name': 'max_part1_night_shifts', 'value': 8, 'description': '【回数上限】パート1の月間夜勤回数'},
            {'name': 'max_part2_late_shifts', 'value': 12, 'description': '【回数上限】パート2の月間遅番回数'},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM shift_constraints WHERE name IN ('max_part1_night_shifts', 'max_part2_late_shifts')")
    # ### end Alembic commands ###
