"""Add workable shifts for part-time 4 users

Revision ID: 3bc0e1850be7
Revises: 3032890fc90d
Create Date: 2026-02-16 18:45:28.103284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc0e1850be7'
down_revision = '3032890fc90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workable_shifts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shift_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_workable_shifts')
    # ### end Alembic commands ###
