"""Add ShiftConstraint model

Revision ID: 6002e006f109
Revises: aea4e6887fb7
Create Date: 2026-02-14 19:56:37.892194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002e006f109'
down_revision = 'aea4e6887fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    # ### Insert default data ###
    op.bulk_insert(
        sa.table(
            'shift_constraints',
            sa.column('name', sa.String),
            sa.column('value', sa.Integer),
            sa.column('description', sa.String),
        ),
        [
            # Staffing - Weekday
            {'name': 'min_employees_weekday_7_16', 'value': 4, 'description': '【人員配置】平日・土曜の7-16時の最低人数'},
            {'name': 'min_employees_weekday_16_20', 'value': 3, 'description': '【人員配置】平日・土曜の16-20時の最低人数'},
            {'name': 'min_employees_weekday_20_07', 'value': 2, 'description': '【人員配置】平日・土曜の20-翌7時の最低人数'},
            # Staffing - Sunday
            {'name': 'min_employees_sunday_7_16', 'value': 4, 'description': '【人員配置】日曜の7-16時の最低人数'},
            {'name': 'min_employees_sunday_16_20', 'value': 4, 'description': '【人員配置】日曜の16-20時の最低人数'},
            {'name': 'min_employees_sunday_20_07', 'value': 2, 'description': '【人員配置】日曜の20-翌7時の最低人数'},
            # Consecutive Work
            {'name': 'max_consecutive_late_night', 'value': 4, 'description': '【連続勤務】遅番・夜勤の最大連続勤務日数'},
            {'name': 'max_consecutive_work', 'value': 5, 'description': '【連続勤務】全勤務の最大連続勤務日数'},
            # Monthly Work Days
            {'name': 'monthly_work_days_kaigo', 'value': 21, 'description': '【月間勤務】「介護員」の月間勤務日数'},
            # Night Shift Rules
            {'name': 'kaigo_night_shift_target', 'value': 10, 'description': '【夜勤】「介護員」の月間夜勤の目標回数'},
            # Soft Constraints (Weights)
            {'name': 'weight_kaigo_night_shift_target', 'value': 5, 'description': '【重み】介護員の夜勤目標回数からの逸脱ペナルティ'},
            {'name': 'weight_part1_night_shift', 'value': 10, 'description': '【重み】パート1の夜勤優先度'},
            {'name': 'weight_part2_late_shift', 'value': 10, 'description': '【重み】パート2の遅番優先度'},
            {'name': 'weight_leader_support_early_shift', 'value': 5, 'description': '【重み】責任者・サポートの早番優先度'},
            {'name': 'weight_avoid_leader_support_same_day', 'value': 20, 'description': '【重み】責任者・サポートの同日勤務回避ペナルティ'},
            {'name': 'weight_minimize_consecutive_work', 'value': 1, 'description': '【重み】連続勤務日数の短縮化へのインセンティブ'},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_constraints')
    # ### end Alembic commands ###
