"""add flexible constraint fields to shift_constraint

Revision ID: 884dd81ba563
Revises: 90e23f18d307
Create Date: 2026-03-28 16:06:21.884929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884dd81ba563'
down_revision = '90e23f18d307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    constraint_type = sa.Enum('HARD', 'SOFT', 'INACTIVE', name='constrainttype')
    constraint_type.create(op.get_bind())

    with op.batch_alter_table('shift_constraints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constraint_type', constraint_type, server_default='INACTIVE', nullable=False))
        batch_op.add_column(sa.Column('penalty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description_jp', sa.String(length=255), nullable=True))
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_constraints', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('description_jp')
        batch_op.drop_column('category')
        batch_op.drop_column('penalty')
        batch_op.drop_column('constraint_type')

    constraint_type = sa.Enum('HARD', 'SOFT', 'INACTIVE', name='constrainttype')
    constraint_type.drop(op.get_bind())
    # ### end Alembic commands ###
