"""add employee_number to user table

Revision ID: 90e23f18d307
Revises: b1ce5878e9b7
Create Date: 2026-03-28 15:14:27.320165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e23f18d307'
down_revision = 'b1ce5878e9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.Integer(), nullable=True))
        batch_op.alter_column('employment_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('MANAGER', 'SUPPORT', 'FULL_TIME', 'PART_TIME_8H', 'PART_TIME_SHORT', 'HOSPITAL_VISIT_SUPPORT', name='employmenttype'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_employee_number'), ['employee_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_number'))
        batch_op.alter_column('employment_type',
               existing_type=sa.Enum('MANAGER', 'SUPPORT', 'FULL_TIME', 'PART_TIME_8H', 'PART_TIME_SHORT', 'HOSPITAL_VISIT_SUPPORT', name='employmenttype'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('employee_number')

    # ### end Alembic commands ###
