"""Add ShiftAssignment model

Revision ID: aea4e6887fb7
Revises: 1041ec8a18d5
Create Date: 2026-02-12 14:40:13.906780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea4e6887fb7'
down_revision = '1041ec8a18d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignments_date'))

    op.drop_table('shift_assignments')
    # ### end Alembic commands ###
