"""allow null times for shift types and add special shifts

Revision ID: b1ce5878e9b7
Revises: fcbb297595b7
Create Date: 2026-03-21 10:19:56.472359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'b1ce5878e9b7'
down_revision = 'fcbb297595b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=True)
    # ### end Alembic commands ###
    
    # --- Manually modified for idempotency ---
    # Define the table structure for querying
    shift_types_table = sa.table('shift_types',
        sa.column('name', sa.String)
    )

    # Get the current connection
    conn = op.get_bind()

    # Define the shifts to be added
    special_shifts = [
        {'name': '休', 'start_time': None, 'end_time': None},
        {'name': '明', 'start_time': None, 'end_time': None},
        {'name': '有', 'start_time': None, 'end_time': None},
    ]
    
    # Get the names of the shifts to be added
    shift_names_to_add = [shift['name'] for shift in special_shifts]

    # Query for existing shifts
    existing_shifts_query = sa.select(shift_types_table.c.name).where(shift_types_table.c.name.in_(shift_names_to_add))
    existing_shifts_result = conn.execute(existing_shifts_query).fetchall()
    existing_shift_names = {row[0] for row in existing_shifts_result}

    # Filter out shifts that already exist
    shifts_to_insert = [shift for shift in special_shifts if shift['name'] not in existing_shift_names]

    # Insert only the new special shifts
    if shifts_to_insert:
        op.bulk_insert(
            sa.table('shift_types',
                sa.column('name', sa.String),
                sa.column('start_time', sa.Time),
                sa.column('end_time', sa.Time)
            ),
            shifts_to_insert
        )


def downgrade():
    # Delete the special shifts
    op.execute("DELETE FROM shift_types WHERE name IN ('休', '明', '有')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=False)
    # ### end Alembic commands ###
