"""allow null times for shift types and add special shifts

Revision ID: b1ce5878e9b7
Revises: fcbb297595b7
Create Date: 2026-03-21 10:19:56.472359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'b1ce5878e9b7'
down_revision = 'fcbb297595b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=True)
    # ### end Alembic commands ###
    
    # Define the table structure for the bulk insert
    shift_types_table = table('shift_types',
        column('name', sa.String),
        column('start_time', sa.Time),
        column('end_time', sa.Time)
    )

    # Insert the special shifts
    op.bulk_insert(shift_types_table,
        [
            {'name': '休', 'start_time': None, 'end_time': None},
            {'name': '明', 'start_time': None, 'end_time': None},
            {'name': '有', 'start_time': None, 'end_time': None},
        ]
    )


def downgrade():
    # Delete the special shifts
    op.execute("DELETE FROM shift_types WHERE name IN ('休', '明', '有')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_types', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=False)
    # ### end Alembic commands ###
