"""Add ShiftGenerationHistory model

Revision ID: b7b67dad01a6
Revises: 6002e006f109
Create Date: 2026-02-14 20:06:37.688350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b67dad01a6'
down_revision = '6002e006f109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('target_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_generation_history')
    # ### end Alembic commands ###
