"""Add visit_time to SpecialDay

Revision ID: bdbc10675dde
Revises: 8f1c392445e5
Create Date: 2026-02-23 07:02:17.016312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbc10675dde'
down_revision = '8f1c392445e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_days', schema=None) as batch_op:
        batch_op.drop_column('visit_time')

    # ### end Alembic commands ###
