"""Make min_max_days_nullable_in_desired_requests

Revision ID: c214f515352e
Revises: bdbc10675dde
Create Date: 2026-03-04 10:19:55.291824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c214f515352e'
down_revision = 'bdbc10675dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desired_work_days_requests', schema=None) as batch_op:
        batch_op.alter_column('min_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desired_work_days_requests', schema=None) as batch_op:
        batch_op.alter_column('max_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_days',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
