"""replace desired_work_days with min_max_range on User

Revision ID: c683c69230a4
Revises: c214f515352e
Create Date: 2026-03-04 12:22:45.382050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c683c69230a4'
down_revision = 'c214f515352e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_work_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_work_days', sa.Integer(), nullable=True))
        batch_op.drop_column('desired_work_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_work_days', sa.INTEGER(), nullable=True))
        batch_op.drop_column('max_work_days')
        batch_op.drop_column('min_work_days')

    # ### end Alembic commands ###
