"""Remove pdf_file_path from ShiftGenerationHistory

Revision ID: db11b882fb88
Revises: 15d8b35a3a42
Create Date: 2026-03-19 14:58:15.602151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db11b882fb88'
down_revision = '15d8b35a3a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_generation_history', schema=None) as batch_op:
        batch_op.drop_column('pdf_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_generation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
