"""Initial migration from current models

Revision ID: dfc57f28c169
Revises: 
Create Date: 2026-02-22 09:51:14.953382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc57f28c169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_constraints')),
    sa.UniqueConstraint('name', name=op.f('uq_shift_constraints_name'))
    )
    op.create_table('shift_generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('target_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_generation_history'))
    )
    op.create_table('shift_types',
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('shift_type_id', name=op.f('pk_shift_types')),
    sa.UniqueConstraint('name', name=op.f('uq_shift_types_name'))
    )
    op.create_table('special_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('staff_increase', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_special_days')),
    sa.UniqueConstraint('date', name=op.f('uq_special_days_date'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('employment_type', sa.Enum('MANAGER', 'SUPPORT', 'FULL_TIME', 'PART_TIME_8H', 'PART_TIME_SHORT', name='employmenttype'), nullable=False),
    sa.Column('desired_work_days', sa.Integer(), nullable=True),
    sa.Column('ng_shifts', sa.String(length=255), nullable=True),
    sa.Column('preferred_night_shifts', sa.Integer(), nullable=True),
    sa.Column('preferred_late_shifts', sa.Integer(), nullable=True),
    sa.Column('preferred_early_shifts', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_work_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('day_off_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_day_off_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_off_requests'))
    )
    op.create_table('desired_work_days_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_desired_work_days_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desired_work_days_requests'))
    )
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], name=op.f('fk_shift_assignments_shift_type_id_shift_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shift_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignments'))
    )
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('user_workable_shifts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], name=op.f('fk_user_workable_shifts_shift_type_id_shift_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_workable_shifts_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'shift_type_id', name=op.f('pk_user_workable_shifts'))
    )
    op.create_table('work_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_work_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_requests'))
    )
    op.create_table('work_request_shifts',
    sa.Column('work_request_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.shift_type_id'], name=op.f('fk_work_request_shifts_shift_type_id_shift_types')),
    sa.ForeignKeyConstraint(['work_request_id'], ['work_requests.id'], name=op.f('fk_work_request_shifts_work_request_id_work_requests')),
    sa.PrimaryKeyConstraint('work_request_id', 'shift_type_id', name=op.f('pk_work_request_shifts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_request_shifts')
    op.drop_table('work_requests')
    op.drop_table('user_workable_shifts')
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignments_date'))

    op.drop_table('shift_assignments')
    op.drop_table('desired_work_days_requests')
    op.drop_table('day_off_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('special_days')
    op.drop_table('shift_types')
    op.drop_table('shift_generation_history')
    op.drop_table('shift_constraints')
    # ### end Alembic commands ###
