"""remove preferred_night_shifts from user

Revision ID: f4a6388ff38d
Revises: f67ae448a515
Create Date: 2026-03-04 18:20:15.044489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a6388ff38d'
down_revision = 'f67ae448a515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_night_shifts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_night_shifts', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
