"""add min and max night shifts to user

Revision ID: f67ae448a515
Revises: c683c69230a4
Create Date: 2026-03-04 18:15:09.034632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67ae448a515'
down_revision = 'c683c69230a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_night_shifts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_night_shifts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('max_night_shifts')
        batch_op.drop_column('min_night_shifts')

    # ### end Alembic commands ###
